services:

  # SQL Server — Microsoft's pre-built image (a whole database engine, as a container)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cicd_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng_Passw0rd!"
    ports:
      - "1433:1433"

  # API — built from Dockerfile
  api:
    build:
      context: .
      dockerfile: CICD_Testing_Project.Api/Dockerfile
    container_name: cicd_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=Workspace;User ID=sa;Password=Str0ng_Passw0rd!;TrustServerCertificate=True;"
    depends_on:
      - db